spring:
  datasource:
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST:localhost}:3306/devconnectorexperiencedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: EDUCATION-SERVICE
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
api:
  profile: http://PROFILE-SERVICE/api/profile
    
